### ISSUE TITLE
how do you do it?

### ISSUE THREAD

**Issue by adbrasi** [jimmm-ai/TimeUi-a-ComfyUi-Timeline-Node#1]
beautiful work
i can't understand, how do you run html, js, css code without python? how do you run the code without _init_.py?????????????

**Comment by jimmm-ai** [comment]
Hi, thanks for the message ! 
The project is still in its early stages and there is no usable node at the moment. The only code available was made in HTML, JS, and CSS for the purpose of the presentation video of the project idea. I am still looking for developers to contribute to the project. I will push some very early code for the final node later today.

**Comment by corbin-hayden13** [comment]
@adbrasi to help answer this: ComfyUI treats the frontend (javascript, html, etc.) and the backend (python) like two separate nodes.  An __init__.py file is required to point to the web directory for the node so ComfyUI knows to register the node you define in Javascript.  The original javascript-only code creates a node and registers it on the frontend which is why comfyui finds it and renders it, but there's nothing working behind the scenes (at least not the frontend node that was originally created).  To make the node work, you have to create a node of the same name, type, and category on the backend then register it in the __init__.py to help comfyui connect the two pieces together and treat them as one singular node.

From experience, this process is very picky.  What I mean is that everything from name, category, node type, inputs, input types, outputs, output types, etc has the be exactly the same between the frontend and the backend, or the backend will override the frontend and the javascript doesn't render what you want it to.  Adding inputs on the frontend translates to "required" inputs on the backend and adding widgets on the frontend translates to "optional" on the backend.  All input types must be exactly the same, and that gets tricky when you start adding combo widgets.

**Comment by corbin-hayden13** [comment]
After taking some more time to investigate exactly how ComfyUI treats nodes, I'd like to clear some things up:
 - ComfyUI doesn't treat the frontend and the backend like two different nodes, instead you can define a node on the frontend by registering a class that extends LGrpahNode like so `class ExampleNode extends LiteGraph.LGraphNode {...)` and this creates a node on the frontend separate from anything on the backend.
 - There's some information about this on the ComfyUI docs, but to create a frontend you have to set the `WEB_DIRECTORY` value in your `__init__.py` to the relative path of your javascript directory, which will typically look like `WEB_DIRECTORY = "./js"` if you have a folder called "js" that's in the same root path as your `__init__.py` file.
 - If you create a node on the backend by following the example python node code from ComfyUI and you want to add custom html to it, you have to catch the backend node as it's rendered on the frontend and operate on it there by first calling `app.registerExtension({...})` within you javascript file that looks like the following:
 
```javascript
app.registerExtension({
  name: "example_extension_name",
  async beforeRegisterNodeDef(nodeType, nodeData, app) {
    const origOnNodeCreated = nodeType.prototype.onNodeCreated;
    nodeType.prototype.onNodeCreated = function () {
      const r = origOnNodeCreated ? origOnNodeCreated.apply(this, arguments) : undefined;
      // Put your code inside this function
      return r;
    }
  }
});
```

By redefining `onNodeCreated` you can hijack the node as it's about to be rendered and add anything you want to it.  What gets tricky is that, while nodeType may look the same when referenced just inside `beforeRegisterNodeDef` versus inside `onNodeCreated`, the context of nodeType changes when inside `onNodeCreated` and it becomes the instance of the node that you're creating.  Thus, when calling `this.addCustomWidget` to add another widget or `this.addDOMWidget` to create space for custom html within the node, you must call this within `onNodeCreated` because that's where `this` has the proper context.

The initial implementation of our custom node used the frontend class definition extending LGraphNode to render the node, but because we have to do some operations on the backend using the backend node, we're refactoring it into the `app.registerExtension` call that it needs to be.

This is being done because any node defined on the frontend with the same node class and name as one on the backend will be overwritten by the node on the backend and thus will not render any custom html potentially added.

**Comment by corbin-hayden13** [comment]
Marking this issue as closed and archiving in wiki [here](https://github.com/jimmm-ai/TimeUi-a-ComfyUi-Timeline-Node/wiki/Relevant-Discussions-and-Questions).
